import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../../Core/theme'
const { font } = theme;
import Text_Size_Type from '../../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    midContainer:{
        flex:2,
        marginTop:'3%'
    },
    userImageView:{
        position:'absolute',
        alignSelf:'center',
        zIndex:1,
        borderRadius:Dimensions.get('window').width*0.5,
    },
    userImage:{
        borderRadius:Dimensions.get('window').width*0.5,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.078 : Dimensions.get('window').height*0.088,
        width:Dimensions.get('window').width*0.175,
    },
    cameraIconView:{
        marginTop:'10%',
        marginLeft:'15%',
        backgroundColor:'#ECEDED',
        borderRadius:Dimensions.get('window').width*0.5,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.03 : Dimensions.get('window').height*0.035,
        width:Dimensions.get('window').width*0.065,
        alignSelf:'center',
        justifyContent:'center',
        alignItems:'center',
        zIndex:1
    },
    userContainer:{
        backgroundColor:'#FFFFFF',
        marginHorizontal:'5%',
        borderRadius:Dimensions.get('window').width*0.02,
        padding:'4%',
        marginVertical:'-7%',
    },
    editIconView:{
        alignSelf:'flex-end',
    },
    detailView:{},
    userName:{
        fontFamily:font.bold,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_6,
        color:'black',
        marginTop:'2%'
    },
    userEmail:{
        fontFamily:font.regular,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_5
    },
    logoutView:{
        borderRadius:Dimensions.get('window').width*0.08,
        paddingVertical:'2%',
        alignItems:'center',
        marginHorizontal:'30%',
        marginTop:'3%'
    },
    logoutText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
        color:'white',
    },
    downContainer:{
        flex:5,
        marginHorizontal:'5%',
        marginTop:'3%'
    },
    listView:{
        backgroundColor:'#FFFFFF',
        paddingHorizontal:'5%',
    },
    line:{
        backgroundColor:'lightgray',
        height:Dimensions.get('window').height*0.001,
        width:Dimensions.get('window').width*0.81
    },
    listItemView:{
        paddingVertical:'5%',
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between'
    },
    listText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    buttonContainer:{
        justifyContent:'center',
        alignItems:'center',
        marginBottom:'3%'
    },
    buttonView:{
        paddingVertical:'3%',
        paddingHorizontal:'25%',
        borderRadius:Dimensions.get('window').width*0.09,
    },
    buttonText:{
        fontFamily:font.bold,
        color:'white',
        fontSize:Text_Size_Type.Text_Type_6,
    },
    inputContainer:{
        marginVertical:Platform.OS === 'ios'? '15%' : '12%',
    },
    inputView:{
        marginVertical:'2%',
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.08,
        paddingVertical:Platform.OS === 'ios'? '4%' : '1%',
        paddingHorizontal:'4%',
        flexDirection:'row',
        alignItems:'center'
    },
    inputText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
        color:'black',
        marginLeft:'3%',
        flex:1,
    },
    iconView:{
        paddingRight:'3%',
        borderRightWidth:0.5
    },

    //Modal Style
    modalWindow:{
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.08,
        padding:'5%',
        marginHorizontal:'5%',
    },
    Title:{
        fontFamily:font.bold,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_8,
        letterSpacing:1,
    },
    Text:{
        fontFamily:font.regular,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_5,
        marginVertical:'3%'
    },
    Button:{
        marginTop:'5%',
        padding:'5%',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:Dimensions.get('window').width*0.5,
    },
    buttonText:{ 
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'white',
    },
    successIcon:{
        alignSelf:'center'
    },
})
export default styles