import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../../Core/theme'
const { colors, font} = theme;
import Text_Size_Type from '../../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    reviewsContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-end',
        marginHorizontal:'8%',
        marginVertical:'3%',
    },
    writereviewsText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        marginLeft:'1%',
    },
    flatList:{
        marginHorizontal:'5%',
        marginBottom:Platform.OS === 'ios'?'40%':'28%',
        backgroundColor:'#FFFFFF',
        borderRadius:Dimensions.get('window').width*0.03,
    },
    listItemContainer:{
        marginHorizontal:'5%',
        borderBottomWidth:0.2,
    },
    listItemView:{
        marginTop:'5%',
        marginBottom:'8%'
    },
    listView:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
        marginBottom:'3%'
    },
    imageContainerReview:{
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
    },
    image:{
        borderRadius:Dimensions.get('window').width*0.8,
        width:Dimensions.get('window').width*0.12,
        height:Dimensions.get('window').height*0.06,
        marginRight:'5%'
    },
    nameText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black'
    },
    timeText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_3,
    },
    ratingContainerReview:{
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
    },
    ratingText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_4,
        color:'black',
        padding:'2%'        
    },
    reviewText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
        textAlign:'justify',
    },

    //Write Review
    imageContainer:{
        alignItems:'center',
        marginVertical:Platform.OS === 'ios'? '12%' : '8%'
    },
    ratingContainer:{
        margin:'5%',
    },
    ratingExpText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_7,
        color:'black',
        textAlign:'center'
    },
    starContainer:{
        marginTop:'3%',
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-around',
        marginHorizontal:'25%'
    },
    inputContainer:{
        marginVertical:'5%',
        marginHorizontal:'5%',
        borderRadius:Dimensions.get('window').width*0.03,
        backgroundColor:'#F5F5F5',
        padding:'2%',
        height:Dimensions.get('window').height*0.17
    },
    input:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
    },
    letterContainer:{
        alignItems:'flex-end',
    },
    letterCount:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_3,
    },
    buttonContainer:{
        marginHorizontal:'18%',
        marginVertical:'5%',
        alignItems:'center',
        borderRadius:Dimensions.get('window').width*0.05,
        justifyContent:'center',
        paddingVertical:'3%',
    },
    buttonText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'white',
    },

     //Modal Style
     modalWindow:{
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.08,
        padding:'5%',
        marginHorizontal:'5%',
    },
    Title:{
        fontFamily:font.bold,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_8,
        letterSpacing:1,
    },
    Text:{
        fontFamily:font.regular,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_5,
        marginVertical:'3%'
    },
    Button:{
        marginTop:'5%',
        padding:'5%',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:Dimensions.get('window').width*0.5,
    },
    buttonText:{ 
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'white',
    },
})
export default styles