import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../../Core/theme'
const { colors, font} = theme;
import Text_Size_Type from '../../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    Flatlist:{
        marginHorizontal:'5%',
        marginBottom:Platform.OS === 'ios' ? '24%':'16%',
        marginTop:Platform.OS === 'ios' ? '2%': 0
    },
    itemContanier:{
        marginVertical:'3%',
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.02,
        flexWrap:'wrap',
        flexDirection:'row',
    },
    discountView:{
        flex:1,
        borderBottomLeftRadius:Dimensions.get('window').width*0.03,
        borderTopLeftRadius:Dimensions.get('window').width*0.03,
        justifyContent:'center',
    },
    circle:{
        width:Dimensions.get('window').width*0.02,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.0135 : Dimensions.get('window').height*0.017,
        backgroundColor:'white',
        borderTopRightRadius:Dimensions.get('window').width*0.5,
        borderBottomRightRadius:Dimensions.get('window').width*0.5,
    },
    discountText:{
        fontFamily:font.bold,
        transform: [{ rotate: '270deg' }],
        fontSize:Text_Size_Type.Text_Type_2,
        color:'white',
        textAlign:'center',
    },
    DetailView:{
        flex:6,
        padding:'4%'
    },
    imageContainer:{
        flexDirection:'row',
        flexWrap:'wrap',
    },
    couponsImage:{
        width:Dimensions.get('window').width*0.1,
        height:Dimensions.get('window').height*0.05,
        marginRight:'3%',
    },
    couponText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
        textAlign:'justify',
        width:Dimensions.get('window').width*0.57
    },
    expiryView:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        marginTop:'8%'
    },
    expiry:{},
    couponExpiryText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
    },
    couponExpiryDate:{
        fontSize:Text_Size_Type.Text_Type_4,
        color:'black',
        fontFamily:font.bold,
    },
    redeemButton:{
        borderRadius:Dimensions.get('window').width*0.05,
        paddingHorizontal:'8%',
        paddingVertical:'1.8%',
        borderWidth:1,
        borderColor:'white',
    },
    redeemButtonText:{
        fontFamily:font.regular,
        color:'white',
        fontSize:Text_Size_Type.Text_Type_4,
    },

    //Coupons Detail
    couponcontainer:{
        flex:1,
    },
    couponview:{
        flex:1,
        padding:'5%'
    },
    logoContainer:{
        flex:5,
        justifyContent:'center',
        alignItems:'center'
    },
    offContainer:{
        flex:2,
        justifyContent:'center',
        alignItems:'center'
    },
    offText:{
        color:'white',
        fontSize:Text_Size_Type.Text_Type_8,
        fontFamily:font.bold,
    },
    expireContainer:{
        flex:1,
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between'
    },
    expireView:{},
    expireText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'white',
        textAlign:'justify'
    },
    bold:{
        fontWeight:'bold'
    },
    jutify:{
        textAlign:'justify',
    },
    paragContainer:{
        flex:2,
        justifyContent:'center',
        alignItems:'center'
    },
    lineBarContainer:{
        flex:1,
        justifyContent:'center',
    },
    lineBarText:{
        fontSize:Text_Size_Type.Text_Type_7,
        color:'white',
        textAlign:'justify',
        fontFamily:font.bold,
    },
    closeContainer:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:'45%',
        borderRadius:Dimensions.get('window').width*0.5,
    },
    icon:{
        borderRadius:Dimensions.get('window').width*0.5,
        alignSelf:'center'
    },
})
export default styles