import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../../Core/theme'
const { colors, font} = theme;
import Text_Size_Type from '../../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    scrollview:{
        marginTop:Platform.OS === 'ios' ? '3%': 0
    },
    adressContainer:{
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.02,
        padding:'4%',
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:'2%',
        marginHorizontal:'5%',
    },
    addressView:{},
    address:{
        flexDirection:'row',
        alignItems:'center',
        marginVertical:'1%'
    },
    addressTitle:{
        marginRight:'2%',
        fontSize:Text_Size_Type.Text_Type_4,
        fontFamily:font.regular,
    },
    adrdressText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_4,
        color:'black'
    },
    editView:{},
    paymentContainter:{
        margin:'5%'
    },
    paymentText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'black',
        marginBottom:'3%',
    },
    selectionBox:{
        marginVertical:'1%',
        paddingVertical:'4%',
        paddingHorizontal:'5%',
        borderRadius:Dimensions.get('window').width*0.02,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    selectionText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    circle:{
        borderWidth:2,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.015 : Dimensions.get('window').height*0.018,
        width:Dimensions.get('window').width*0.033,
        borderRadius:Dimensions.get('window').width*0.04
    },
    orderContainter:{
        marginHorizontal:'5%',
    },
    Flatlist:{
        marginBottom:'15%',
    },
    itemContanier:{
        flex:1,
        marginBottom:'3%',
        paddingHorizontal:'2%',
        backgroundColor:'white',
        flexDirection:'row',
        borderRadius:Dimensions.get('window').width*0.02
    },
    itemImageView:{
        backgroundColor:'rgba(245, 245, 245, 1)',
        marginVertical:'2.3%',
        paddingVertical:'3%',
        paddingHorizontal:'9%',
        borderRadius:Dimensions.get('window').width*0.015,
    },
    itemImage:{
        width:Platform.OS === 'ios'? Dimensions.get('window').width*0.14 : Dimensions.get('window').width*0.14,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.08 : Dimensions.get('window').height*0.095,
        alignSelf:'center'
    },
    itemDetailContainer:{
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        marginLeft:'3%',
        justifyContent:'space-between',
    },
    itemText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    itemNameText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
        marginBottom:'3%'
    },
    itemPriceText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_4,
        marginVertical:'5%'
    },
    buttonPlaceOrder:{
        position:'absolute',
        borderRadius:Dimensions.get('window').width*0.09,
        paddingHorizontal:'13%',
        paddingVertical:'2.8%',
        bottom:'2%',
        alignSelf:'center',
        justifyContent:'center'
    },
    placeOrderText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        textAlign:'center',
        color:'white'
    },

    //Delivery Form
    scrollViewForm:{
        marginHorizontal:'5%',
        marginTop:Platform.OS === 'ios' ? '5%': 0,
    },
    addressInputContainer:{
        marginBottom:Platform.OS === 'ios' ? '3%' : 0,

    },
    nameTitleView:{
        flexDirection:'row',
        marginVertical:'3%',
    },
    inputFieldTitle:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        marginLeft:'3%',
    },
    inputText:{
        flex:1,
        borderRadius:Dimensions.get('window').width*0.02,
        fontSize:Text_Size_Type.Text_Type_5,
        backgroundColor:'white',
        paddingHorizontal:'5%',
        paddingVertical:'2.5%',
        elevation:2,
        color:'black',
        fontFamily:font.bold,
    },
    buttonAdressSave:{
        marginVertical:'5%',
        marginHorizontal:'12%',
        padding:'3%',
        borderRadius:Dimensions.get('window').width*0.08,
    },

    //Shipping Adress
    shippingFlatlist:{
        marginHorizontal:'5%',
        marginTop:'2%',
        height:Dimensions.get('window').height*0.85
    },
    adressContanier:{
        backgroundColor:'white',
        padding:'3%',
        borderRadius:Dimensions.get('window').width*0.03,
        justifyContent:'space-between',
        marginVertical:'2%'
    },
    adressView:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
        marginBottom:'7%',
        alignItems:'center'
    },
    addressUserText:{
        fontSize:Text_Size_Type.Text_Type_5,
        fontFamily:font.bold,
        color:'black'
    },
    addressText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
        width:Dimensions.get('window').width*0.65,
    },
    iconView:{
        borderRadius:Dimensions.get('window').width*0.05,
        height:Dimensions.get('window').width*0.05,
        width:Dimensions.get('window').width*0.05,
        justifyContent:'center',
        padding:'1%',
        alignItems:'center'
    },
    iconSepView:{
        flexDirection:'row',
        flexWrap:'wrap',
    },
    iconSepButton:{
    },
    addButtonContainer:{
        marginTop:'5%',
        alignItems:'center',
    },
    addButtonView:{
        paddingHorizontal:'1.5%',
        paddingVertical:'1%',
        borderRadius:Dimensions.get('window').width*0.05,
        justifyContent:'center',
    },
    addButtonText:{
        marginVertical:'2%',
        fontSize:Text_Size_Type.Text_Type_5,
        fontFamily:font.bold,
    },
})
export default styles