import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../../Core/theme'
const { colors,font } = theme;
import Text_Size_Type from '../../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    Flatlist:{
        flex:1,
        marginHorizontal:'5%',
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.4: Dimensions.get('window').height*0.45,
        marginTop:Platform.OS === 'ios' ? '3%': 0
    },
    itemContanier:{
        flex:1,
        marginVertical:'2%',
        paddingHorizontal:'2%',
        backgroundColor:'white',
        flexDirection:'row',
        borderRadius:Dimensions.get('window').width*0.02
    },
    itemImageView:{
        backgroundColor:'rgba(245, 245, 245, 1)',
        marginVertical:'2.3%',
        paddingVertical:'4%',
        paddingHorizontal:'9%',
        borderRadius:Dimensions.get('window').width*0.015,
    },
    itemImage:{
        width:Platform.OS === 'ios'? Dimensions.get('window').width*0.16 : Dimensions.get('window').width*0.14,
        height:Platform.OS === 'ios'?Dimensions.get('window').height*0.085 : Dimensions.get('window').height*0.09,
        alignSelf:'center'
    },
    itemDetailContainer:{
        justifyContent:'center',
        margin:'5%',
    },
    itemNameText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
    },
    itemCompanyText:{
        fontSize:Text_Size_Type.Text_Type_4,
        fontFamily:font.bold,
    },
    listContatiner:{
        flexDirection:'row',
        flexWrap:'wrap',
        marginTop:'5%',
    },
    itemPriceText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
    },
    selectItem:{
        backgroundColor:'rgba(245, 245, 245, 1)',
        flexDirection:'row',
        borderRadius:Dimensions.get('window').width*0.04,
        alignItems:'center',
        marginLeft:'36%',
        paddingHorizontal:'5%',
        flexWrap:'wrap',
    },
    operator:{
        fontSize:Text_Size_Type.Text_Type_8,
        fontWeight:'bold',
    },
    operatorText:{
        fontSize:Text_Size_Type.Text_Type_6,
        paddingHorizontal:'4%',
    },
    downContainer:{
        flex:1,
        marginHorizontal:'5%',
    },
    textFieldContainer:{
        backgroundColor:'white',
        flexDirection:'row',
        flexWrap:'wrap',
        marginTop:'5%',
        borderRadius:Dimensions.get('window').width*0.02,
        justifyContent:'space-between',
        paddingHorizontal:'2%',
        paddingVertical:Platform.OS === 'ios'? '2,5%' : 0,
        alignItems:'center',
        elevation:2,

        shadowColor: '#171717',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    codeInput:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        flex:1,
    },
    buttonApply:{
        paddingHorizontal:'5%',
        paddingVertical:'2.5%',
        borderRadius:Dimensions.get('window').width*0.03,
    },
    applyText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
        color:'white'
    },
    totalContainer:{
        flex:3,
        justifyContent:'flex-end',
        marginTop:'12%',
    },
    totalView:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginVertical:'1%',
    },
    subtotalText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    totalText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    itemView:{
        flexDirection:'row',
        alignItems:'center'
    },
    itemText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        paddingRight:'2%'
    },
    subpriceText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    priceText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
    },
    proceedContainer:{
        flex:1,
        marginHorizontal:'12%',
        marginVertical:'5%'
    },
    buttonProceed:{
        borderRadius:Dimensions.get('window').width*0.05,
        paddingVertical:'3.7%',
    },
    proceedText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_7,
        color:'white',
        textAlign:'center'
    },
    cartContainer:{
        flex:1,
        justifyContent:'center',
    },
    emptyCartContainer:{
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:'5%'
    },
    emptycartText:{
        fontFamily:font.bold,        
        fontSize:Text_Size_Type.Text_Type_11,
        color:'black',
        marginTop:'5%'
    },
    emptycartDetailText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_6,
        textAlign:'center',
    },
    buttonStart:{
        marginTop:'15%',
        borderRadius:Dimensions.get('window').width*0.06,
        backgroundColor:colors.themeColor,
        paddingVertical:'3%',
        paddingHorizontal:'20%',
    },
    startShoppingText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_7,
        color:'white',
    },
    deleteContainer:{
        marginVertical:'2%',
        flex:1
    },
    deleteView:{
        borderTopRightRadius:Dimensions.get('window').width*0.04,
        marginHorizontal:'4%',
        marginVertical:'12%',
    },

    //Modal Style
    modalWindow:{
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.08,
        padding:'5%',
        marginHorizontal:'5%',
    },
    Title:{
        fontFamily:font.bold,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_8,
        color:colors.themeColor,
        letterSpacing:1,
    },
    Text:{
        fontFamily:font.regular,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_5,
        marginVertical:'3%'
    },
    Button:{
        marginTop:'5%',
        padding:'5%',
        backgroundColor:colors.themeColor,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:Dimensions.get('window').width*0.5,
    },
    buttonText:{ 
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'white',
    },
    successIcon:{
        alignSelf:'center'
    },
})
export default styles