import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../../Core/theme'
const { colors,font } = theme;
import Text_Size_Type from '../../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    orderContainer:{
        flex:2,
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.03,
        padding:'4%',
        marginVertical:'3%',
        marginHorizontal:'5%',
    },
    newView:{
        marginBottom:'5%'
    },
    orderIdText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_4,
        color:'black'
    },
    trackContainer:{
        flexDirection:'column'
    },
    trackView:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
        alignItems:'center'
    },
    dateText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_4,
    },
    userDataText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
    },
    circle:{
        borderRadius:Dimensions.get('window').width*0.5,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.008 : Dimensions.get('window').height*0.009,
        width:Dimensions.get('window').width*0.018,
        backgroundColor:colors.themeColor,
    },
    selectCircle:{
        borderRadius:Dimensions.get('window').width*0.5,
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.028 : Dimensions.get('window').height*0.032,
        width:Dimensions.get('window').width*0.061,
        backgroundColor:colors.themeColor,
        alignItems:'center',
        justifyContent:'center'
    },
    line:{
        height:Dimensions.get('window').height*0.004,
        width:Dimensions.get('window').width*0.23,
    },
    Flatlist:{
        flex:9,
        marginBottom:Platform.OS === 'ios'? '5%' : '1%',
        marginHorizontal:'5%',
    },
    trackingText:{
        marginVertical:'2%',
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'black',
    },
    itemContanier:{
        marginVertical:'2%',
        padding:'4%',
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.03
    },
    itemView:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    itemIdText:{
        fontSize:Text_Size_Type.Text_Type_4,
        fontFamily:font.bold,
    },
    deliverButton:{
        borderRadius:Dimensions.get('window').width*0.04,
        paddingHorizontal:'5%',
        paddingVertical:'1%'
    },
    deliverButtonText:{
        color:'white',
        fontSize:Text_Size_Type.Text_Type_4,
    },
    ItemViewDown:{
        flexDirection:'row',
        flexWrap:'wrap',
    },
    itemImageView:{
        backgroundColor:'rgba(245, 245, 245, 1)',
        marginTop:'2.3%',
        paddingHorizontal:'10%',
        paddingVertical:'2%',
        borderRadius:Dimensions.get('window').width*0.02,
        justifyContent:'center'
    },
    itemImage:{
        width:Dimensions.get('window').width*0.15,
        height:Dimensions.get('window').height*0.087,
        alignSelf:'center',
    },
    itemDetailContainer:{
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        marginLeft:'3%',
        justifyContent:'space-between',
    },
    itemText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    itemNameText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
        marginBottom:'3%'
    },
    itemPriceText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_4,
        marginVertical:'5%'
    },

    //Confirm Order
    ConfirmContainer:{
        flex:1,
        marginHorizontal:'5%',
    },
    imageContainer:{
        flex:7,
        alignSelf:'center',
        justifyContent:'center'
    },
    thankyouContainer:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    },
    thankyouText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_7,
        color:'black',
    },
    orderNumContainer:{
        flex:1,
        alignItems:'center',
    },
    orderNumText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    blackColor:{
        color:'black'
    },
    subTotalContainer:{
        flex:2,
        marginVertical:'8%',
        justifyContent:'flex-end',
        borderTopWidth:0.2
    },
    subTotalView:{
        marginVertical:'1%',
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between'
    },
    totaText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    totalAmount:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    buttonSubmit:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:Dimensions.get('window').width*0.08,
        marginHorizontal:'10%',
        marginBottom:Platform.OS === 'ios'? '7%': '5%'
    },
    buttonText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'white',
    },

    // Place order
    heading:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        margin:Platform.OS === 'ios'? '4%' : '3%'
    },
    placeOrderContainer:{
        flex:2,
        backgroundColor:'white',
        marginHorizontal:'5%',
        padding:'4%',
        borderRadius:Dimensions.get('window').width*0.03,
    },
    placeTextHeading:{
        marginVertical:'1%',
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black'
    },
    placeText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    placeOrderFlatlist:{
        flex:5,
        marginHorizontal:'5%'
    },
    placeItemContanier:{
        marginVertical:'2%',
        padding:'2%',
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.03,
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
    },
    placeItemImageView:{
        backgroundColor:'rgba(245, 245, 245, 1)',
        marginTop:'2.5%',
        paddingHorizontal:'7%',
        paddingVertical:'2%',
        borderRadius:Dimensions.get('window').width*0.02,
    },
    placeItemDetailContainer:{
        flex:1,
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
        marginLeft:'3%',
    },
    placeItemNameText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
        marginBottom:'3%',
    },
    placeItemPriceText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_4,
        marginVertical:'5%'
    },
    placeItemText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    totalContainer:{
        flex:2,
        justifyContent:'flex-end',
        marginHorizontal:Platform.OS === 'ios'? '4%' : '3%',
    },
    totalView:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginVertical:'0.5%',
    },
    subtotalText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    totalText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    placeitemView:{
        flexDirection:'row',
        alignItems:'center'
    },
    itemText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        paddingRight:'2%'
    },
    subpriceText:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
    },
    priceText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
    },
    confirmContainer:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:'15%',
        marginVertical:Platform.OS === 'ios'? '6%': '2%',
        borderRadius:Dimensions.get('window').width*0.5,
    },
    confirmText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_7,
        color:'white',
    }
})
export default styles