import { StyleSheet, Dimensions, Platform } from 'react-native';
import theme from '../../Core/theme'
const { colors, font } = theme;
import Text_Size_Type from '../../Components/Font'

const styles= StyleSheet.create({
    container:{
        flex:1,
    },
    abc:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
    },
    touchButton:{
        marginHorizontal:'5%',
        marginTop:Platform.OS === 'ios'? '10%': '4%',
        marginBottom:'28%',
    },
    icon:{
        margin:'5%'
    },
    rectangle:{
        alignItems:'center',
        backgroundColor:'white',
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.22 : Dimensions.get('window').height*0.21,
        borderBottomLeftRadius:Dimensions.get('window').width*0.2,
        borderBottomRightRadius:Dimensions.get('window').width*0.2,
        padding:'5%',
    },
    signUpImage:{
        alignSelf:'center',
        marginTop:Platform.OS === 'ios'? '27%' : '-2%',
        height:Platform.OS === 'ios'? Dimensions.get('window').height*0.14:Dimensions.get('window').height*0.16,
    },
    skipText:{
        fontSize:Text_Size_Type.Text_Type_5,
        fontFamily:font.bold,
    },
    SignupContainer:{
        alignItems:'center',
        marginVertical:'2%'
    },
    textRegister:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_8,
        letterSpacing:0.6,
    },
    text:{
        opacity:0.6,
        fontSize:Text_Size_Type.Text_Type_5,
        fontFamily:font.regular,
    },
    formContainer:{
        backgroundColor:'white',
        marginVertical:'2%',
        marginHorizontal:'5%',
        paddingHorizontal:'6%',
        paddingVertical:'1%',
        borderRadius:Dimensions.get('window').width*0.06,
    },
    checkBox:{
        marginTop:'3%',
        flexDirection:'row',
        alignItems:'center',
    },
    checkBoxText:{
        marginTop:'1%',
        marginLeft:'3%',
        fontSize:Text_Size_Type.Text_Type_5,
        fontFamily:font.regular,
    },
    termService:{
        fontSize:Text_Size_Type.Text_Type_5,
        fontFamily:font.regular,
    },
    underlineText:{
        textDecorationLine:'underline',
    },
    lowerRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:'4%',
    },
    textSignup:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'black',
    },
    button:{
        borderRadius:Dimensions.get('window').width*0.1,
        paddingHorizontal:'5.5%',
        paddingVertical:'2%'
    },
    social:{
        marginTop:'4%'
    },
    topLineSpace:{
        marginTop:'2%'
    },
    topSpace:{
        marginTop:'10%'
    },
    connectRow:{
        marginVertical:'4%',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    socialIconRow:{
        flexDirection:'row',
    },
    link:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        color:'black',
    },
    forgetView:{
        alignItems:'center',
        marginTop:'8%',
        marginBottom:'3%'
    },
    forgetText:{
        fontSize:Text_Size_Type.Text_Type_6,
        fontFamily:font.regular,
    },
    modalWindow:{
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.08,
        padding:'5%'
    },
    closeIcon:{
        alignSelf:'flex-end',
    },
    forgetTitle:{
        fontFamily:font.bold,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_7,
        marginTop:'5%',
        letterSpacing:1,
    },
    labelText:{
        fontFamily:font.regular,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_5,
        marginTop:'2%'
    },
    submitButton:{
        borderRadius:Dimensions.get('window').width*0.04,
        marginHorizontal:'15%',
        marginVertical:'5%',
        paddingVertical:'5%'
    },
    submitText:{
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_5,
        textAlign:'center',
        color:'white',
    },
    otpView:{
        marginTop:'3%',
        flexDirection:'row',
        justifyContent:'space-evenly',
        alignItems:'center'
    },
    otpInputView:{
        backgroundColor:'#F5F5F5',
        marginTop:'3%',
        borderRadius:Dimensions.get('window').width*0.02,
        paddingHorizontal:'3%',
        borderWidth:1,
    },
    otpInput:{
        fontFamily:font.regular,
        fontSize:Text_Size_Type.Text_Type_5,
        textAlign:'center',
    },
    successIcon:{
        alignSelf:'center'
    },
     //Alert Modal Style
    alertModalWindow:{
        backgroundColor:'white',
        borderRadius:Dimensions.get('window').width*0.08,
        padding:'5%',
        marginHorizontal:'5%',
    },
    alertTitle:{
        fontFamily:font.bold,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_8,
        color:colors.themeColor,
        letterSpacing:1,
    },
    alertText:{
        fontFamily:font.regular,
        textAlign:'center',
        fontSize:Text_Size_Type.Text_Type_5,
        marginVertical:'3%'
    },
    alertButton:{
        marginTop:'5%',
        padding:'5%',
        backgroundColor:colors.themeColor,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:Dimensions.get('window').width*0.5,
    },
    alertButtonText:{ 
        fontFamily:font.bold,
        fontSize:Text_Size_Type.Text_Type_6,
        color:'white',
    },
})
export default styles;