
const font = {
  regular: "ProductSans-Regular",
  bold: "ProductSans-Bold",
  italic:"ProductSans-Italic",
  boldItlaic:"ProductSans-BoldItalic",
}
const colors = {
  //orange
  // themeColor:'#FF7466',
  //blue
  // themeColor:'#009DFF',

  orangetheme:'#FF7466',
  orangeBackgroundColor:'#FFF5EA',

  bluetheme:'#009DFF',
  blueBackgroundColor:'#F1F5FD',

  activethemeborder:'red',
  orderTrackColor:'#EAE7E7',
  shippingAdressColor:'#BCBCBC',
  
  App_Name_Color:'white',
  carouselLine:'#C0C0C0',
  titleTextColor:'black',
  nextButtonColor:'white',
  checkBoxChecked:'green',
  checkBoxUnChecked:'white',
  activeTextInputColor:'black',
  selcetedColorone:'#AE9B7A',
  selcetedColorSecond:'#FFB9AC',
  selcetedColorThird:'#9EAD9B',
  selcetedColorFour:'#791C02',
  filtercolorone:'#FF7466',
  filtercolortwo:'#009DFF',
  filtercolorthree:'#FF913D',
  filtercolorfour:'#C40000',
  filtercolorfive:'#79CE47',
  filtercolorsix:'#6494F3',
}
const icons = {
  fb: require("../assets/icons/ic_facebook.png"),
  google: require("../assets/icons/ic_google.png"),
  home: require("../assets/icons/ic_home.png"),
  heart: require("../assets/icons/ic_heart.png"),
  filter: require("../assets/icons/ic_filter.png"),
  garbage: require("../assets/icons/ic_garbage.png"),
  notification: require("../assets/icons/ic_notification.png"),
  bag: require("../assets/icons/ic_bag.png"),
  user: require("../assets/icons/ic_user.png"),
  edit: require("../assets/icons/ic_edit.png"),
  street: require("../assets/icons/ic_street.png"),
  city: require("../assets/icons/ic_city.png"),
  state: require("../assets/icons/ic_state.png"),
  phone: require("../assets/icons/ic_phone.png"),
  zip: require("../assets/icons/ic_zip.png"),
  countrycalling: require("../assets/icons/ic_countrycalling.png"),
  country: require("../assets/icons/ic_county.png"),
  shopping: require("../assets/icons/shopping.png"),
  camera: require("../assets/icons/ic_camera.png"),
  forawrd: require("../assets/icons/ic_forward.png"),
  username: require("../assets/icons/name_ic.png"),
  useremail: require("../assets/icons/email_ic.png"),
  userphone: require("../assets/icons/phone_ic.png"),
  userdob: require("../assets/icons/birthday_ic.png"),
  useradress: require("../assets/icons/adress_ic.png"),
  update: require("../assets/icons/ic_update.png"),
  tick: require("../assets/icons/ic_tick.png"),
  pen: require("../assets/icons/ic_pen.png"),
  startfill: require("../assets/icons/ic_star_fill.png"),
  star: require("../assets/icons/ic_star.png"),
  cardchip: require("../assets/icons/cardchip.png"),
  cardcode: require("../assets/icons/cardcode.png"),
  notification: require("../assets/icons/notification.png"),
  orderdeliver: require("../assets/icons/orderdeliver.png"),
  send: require("../assets/icons/ic_send.png"),
  cart: require("../assets/icons/shoppingcart.png"),
}
const images = {
  cartLogo: require("../assets/images/cartLogo.png"),
  carousel1: require("../assets/images/carousel1.png"),
  carouselb1: require("../assets/images/carouselb1.png"),
  carousel2: require("../assets/images/carousel2.png"),
  carouselb2: require("../assets/images/carouselb2.png"),
  carousel3: require("../assets/images/carousel3.png"),
  carouselb3: require("../assets/images/carouselb3.png"),
  backIcon: require("../assets/images/backIcon.png"),
  nextIcon: require("../assets/images/nextIcon.png"),
  rectangleImageRound: require("../assets/images/rectangleImageRound.png"),
  SignUp: require("../assets/images/SignUp.png"),
  SignIn: require("../assets/images/SignIn.png"),
  success: require("../assets/images/success.png"),
  itemImage: require("../assets/images/item.png"),
  carouselImage: require("../assets/images/items.png"),
  emptyCart: require("../assets/images/emptycart.png"),
  emptyCart2: require("../assets/images/emptycart2.png"),
  garbage: require("../assets/images/garbage.png"),
  user: require("../assets/images/userImage.jpeg"),
  coupon: require("../assets/images/couponlogo.png"),
  reviewOrange: require("../assets/images/review.png"),
  reviewBlue:  require("../assets/images/reviewBlue.png"),
  companylogo: require("../assets/images/companyLogo.png"),
  graylayer: require("../assets/images/greyLayer.png"),
  confirmationOrangelogo: require("../assets/images/confirmation.png"),
  confirmationBluelogo: require("../assets/images/ConfirmationBlue.png"),
  visaLogo: require("../assets/images/VisaLogo.png"),
  cardLogo: require("../assets/images/cardLogo.png"),

}
const strings = {
  themeselection:"Select App Theme Color",
  app_name: "DXP",
  brand_name: "brand tagline",
  carouselText1:"Explorer les produits",
  carouselText2:"Paiements faciles",
  carouselText3:"Livraison rapide",
  next:"Suivant",
  Register:"S'inscrire",
  Welcome:"Content de te revoir",
  backtologin:"Retour connexion",
  SignUp:"S'inscrire",
  SignIn:"Se Connecter",
  login:"Connexion",
  TermOfServices:"Terms of Services",
  forgetText:"Mot de passe oublié",
  questionMark:"?",
  home:"Acceuil",
  filter:"Filters",
  whishlist:"Liste de souhaits",
  mycart:"Mon Panier",
  delivery:"Livraison",
  orderDetail:"Détails de la commande",
  deliveryaddress:"Adresse de livraison",
  Notification:"Notification",
  messages:"Messages",
  Confirmation:"Confirmation",
  wallet:"porte monnaie",
  wallets:"Porte Feuilles",
  messages:"Messages",
  myorder:"Mes commandes",
  shippingadressess:"Adresse de livraison",
  coupons:"Coupons",
  setting:"Reglages",
  editprofile:"Editer le profil",
  shippingadress:"Adresse de livraison",
  setting:"Reglages",
  myprofile:"Mon profile",
  logout:"Deconnexion",
  shipping:"Livraison",
  reviews:"Reviews",
  writeareview:"Write a Review",
  coupons:"Coupons",
  couponsdetail:"Coupons Detail",
  customersupport:"Customer Support",
  adtocart:"Ajouter au panier",
  outofstock:"Out of stock",
  skip:"Passer",
  formName:"Name",
  formPhone:"Phone Number",
  formEmail:"Email",
  formPassword:"Mot de Passe",
  formConfirmPassword:'Re-Enter Password',
  newpassword:"Nouveau Mot de Passe",
  submit:"Soumettre",
  userName:"User Name",
  userEmail:"User Email",
  otp:"OTP",
  resetpassword:"Reset Password",
  success:"Success",
  backprofile:"Back To Login",
  buybutton:'Buy',
  buynowbutton:"Acheter",
  apply:'Appliquer ',
  total:"Total",
  subtotal:"Sous-Total",
  item:"items",
  proceedtocheckout:"Proceder au paiement",
  emptyCart:"Whoops!! Cart is Empty",
  emptyCartDetail:"You wil find a lot of interesting thing in our 'Site'",
  startshopping:"Start Shopping",
  street:"Rue",
  city:"Ville",
  state:"État/Province",
  zipcode:"Code postal",
  countrycallingcode:"Indicatif téléphonique du pays",
  country:"Pays",
  paymentMethod:"Methode de Paiement",
  cashondelivery:"Paiement à la Livrason",
  creditcard:"Credit/Debit Card",
  netbanking:"Virement Bancaire",
  Orderdetails:"Détails de la commande",
  placeorder:"Place Order",
  confirmorder:"Confirmer la commande",
  categories:"Categories",
  color:"Colors",
  priceRange:"Échelle  prix",
  apply:"Appliquer",
  clearall:"Tous effacer",
  save:"Save",
  orderid:"Order ID : #",
  tracking:"Suivie",
  delivered:"Livré",
  addnewadress:"Ajouter une nouvelle adresse",
  off:"off",
  discount:"Discount",
  redeem:"Redeem",
  expires:"Expires",
  rateyourexperiencewithus:"Rate your Experience with Us",
  recenttransaction:"recent tRANSACTION",
  thankyouforshopping:"Merci pour vos achats",
  save:"sauvegarder",
  testText:".",
  ops:"Oops!",
  congras:"Felicitations",
  congrasMessage:"Connectez-vous maintenant avec le même identifiant",
  updateMessage:"Veuillez à nouveau vous connecter",
  registered:"Inscrit-e",
  okay:"Ok",
  alertMessage:"S'il vous plait Connectez-vous d'abord",
  addtocart:"a ajouté au panier",
  addtowhishlist:"a ajouté au Souhaits",
  recordupdate:"L'enregistrement a été mis à jour!",
  cart:'Panier',
  themeselection:"Choisir Theme"
}
export default { font, icons, strings, colors, images }
