
const font = {
  regular: "ProductSans-Regular",
  bold: "ProductSans-Bold",
  italic:"ProductSans-Italic",
  boldItlaic:"ProductSans-BoldItalic",
}
const colors = {
  //orange
  // themeColor:'#FF7466',
  //blue
  // themeColor:'#009DFF',

  orangetheme:'#FF7466',
  orangeBackgroundColor:'#FFF5EA',

  bluetheme:'#009DFF',
  blueBackgroundColor:'#F1F5FD',

  activethemeborder:'red',
  orderTrackColor:'#EAE7E7',
  shippingAdressColor:'#BCBCBC',
  
  App_Name_Color:'white',
  carouselLine:'#C0C0C0',
  titleTextColor:'black',
  nextButtonColor:'white',
  checkBoxChecked:'green',
  checkBoxUnChecked:'white',
  activeTextInputColor:'black',
  selcetedColorone:'#AE9B7A',
  selcetedColorSecond:'#FFB9AC',
  selcetedColorThird:'#9EAD9B',
  selcetedColorFour:'#791C02',
  filtercolorone:'#FF7466',
  filtercolortwo:'#009DFF',
  filtercolorthree:'#FF913D',
  filtercolorfour:'#C40000',
  filtercolorfive:'#79CE47',
  filtercolorsix:'#6494F3',
}
const icons = {
  fb: require("../assets/icons/ic_facebook.png"),
  google: require("../assets/icons/ic_google.png"),
  home: require("../assets/icons/ic_home.png"),
  heart: require("../assets/icons/ic_heart.png"),
  filter: require("../assets/icons/ic_filter.png"),
  garbage: require("../assets/icons/ic_garbage.png"),
  notification: require("../assets/icons/ic_notification.png"),
  bag: require("../assets/icons/ic_bag.png"),
  user: require("../assets/icons/ic_user.png"),
  edit: require("../assets/icons/ic_edit.png"),
  street: require("../assets/icons/ic_street.png"),
  city: require("../assets/icons/ic_city.png"),
  state: require("../assets/icons/ic_state.png"),
  phone: require("../assets/icons/ic_phone.png"),
  zip: require("../assets/icons/ic_zip.png"),
  countrycalling: require("../assets/icons/ic_countrycalling.png"),
  country: require("../assets/icons/ic_county.png"),
  shopping: require("../assets/icons/shopping.png"),
  camera: require("../assets/icons/ic_camera.png"),
  forawrd: require("../assets/icons/ic_forward.png"),
  username: require("../assets/icons/name_ic.png"),
  useremail: require("../assets/icons/email_ic.png"),
  userphone: require("../assets/icons/phone_ic.png"),
  userdob: require("../assets/icons/birthday_ic.png"),
  useradress: require("../assets/icons/adress_ic.png"),
  update: require("../assets/icons/ic_update.png"),
  tick: require("../assets/icons/ic_tick.png"),
  pen: require("../assets/icons/ic_pen.png"),
  startfill: require("../assets/icons/ic_star_fill.png"),
  star: require("../assets/icons/ic_star.png"),
  cardchip: require("../assets/icons/cardchip.png"),
  cardcode: require("../assets/icons/cardcode.png"),
  notification: require("../assets/icons/notification.png"),
  orderdeliver: require("../assets/icons/orderdeliver.png"),
  send: require("../assets/icons/ic_send.png"),
  cart: require("../assets/icons/shoppingcart.png"),
}
const images = {
  cartLogo: require("../assets/images/cartLogo.png"),
  carousel1: require("../assets/images/carousel1.png"),
  carouselb1: require("../assets/images/carouselb1.png"),
  carousel2: require("../assets/images/carousel2.png"),
  carouselb2: require("../assets/images/carouselb2.png"),
  carousel3: require("../assets/images/carousel3.png"),
  carouselb3: require("../assets/images/carouselb3.png"),
  backIcon: require("../assets/images/backIcon.png"),
  nextIcon: require("../assets/images/nextIcon.png"),
  rectangleImageRound: require("../assets/images/rectangleImageRound.png"),
  SignUp: require("../assets/images/SignUp.png"),
  SignIn: require("../assets/images/SignIn.png"),
  success: require("../assets/images/success.png"),
  itemImage: require("../assets/images/item.png"),
  carouselImage: require("../assets/images/items.png"),
  emptyCart: require("../assets/images/emptycart.png"),
  emptyCart2: require("../assets/images/emptycart2.png"),
  garbage: require("../assets/images/garbage.png"),
  user: require("../assets/images/userImage.jpeg"),
  coupon: require("../assets/images/couponlogo.png"),
  reviewOrange: require("../assets/images/review.png"),
  reviewBlue:  require("../assets/images/reviewBlue.png"),
  companylogo: require("../assets/images/companyLogo.png"),
  graylayer: require("../assets/images/greyLayer.png"),
  confirmationOrangelogo: require("../assets/images/confirmation.png"),
  confirmationBluelogo: require("../assets/images/ConfirmationBlue.png"),
  visaLogo: require("../assets/images/VisaLogo.png"),
  cardLogo: require("../assets/images/cardLogo.png"),

}
const strings = {
  themeselection:"Select App Theme Color",
  app_name: "e-commerce",
  brand_name: "brand tagline",
  carouselText1:"Explore Products",
  carouselText2:"Easy Payments",
  carouselText3:"Fast Delivery",
  next:"Next",
  Register:"Register",
  Welcome:"Welcome Back",
  backtologin:"Back to Login",
  SignUp:"Sign up",
  SignIn:"Sign In",
  login:"Log in",
  TermOfServices:"Terms of Services",
  forgetText:"Forgot Password",
  questionMark:"?",
  home:"Home",
  filter:"Filters",
  whishlist:"Whishlist",
  mycart:"My Cart",
  delivery:"Delivery",
  orderDetail:"Order Detail",
  deliveryaddress:"Delivery Address",
  Notification:"Notification",
  messages:"Messages",
  Confirmation:"Confirmation",
  wallet:"Wallet",
  wallets:"Wallets",
  messages:"Messages",
  myorder:"My Orders",
  shippingadressess:"Shipping Addressess",
  coupons:"Coupons",
  setting:"Settings",
  editprofile:"Edit Profile",
  shippingadress:"Shipping Address",
  setting:"Settings",
  myprofile:"My Profile",
  logout:"Logout",
  shipping:"Shipping",
  reviews:"Reviews",
  writeareview:"Write a Review",
  coupons:"Coupons",
  couponsdetail:"Coupons Detail",
  customersupport:"Customer Support",
  adtocart:"ADD to Cart",
  outofstock:"Out of stock",
  skip:"Skip",
  formName:"Name",
  formPhone:"Phone Number",
  formEmail:"Email",
  formPassword:"Password",
  formConfirmPassword:'Re-Enter Password',
  newpassword:"New Password",
  submit:"Submit",
  userName:"User Name",
  userEmail:"User Email",
  otp:"OTP",
  resetpassword:"Reset Password",
  success:"Success",
  backprofile:"Back To Login",
  buybutton:'Buy',
  buynowbutton:"buy now",
  apply:'Apply ',
  total:"Total",
  subtotal:"Sub Total",
  item:"items",
  proceedtocheckout:"Proceed to Checkout",
  emptyCart:"Whoops!! Cart is Empty",
  emptyCartDetail:"You wil find a lot of interesting thing in our 'Site'",
  startshopping:"Start Shopping",
  street:"Street",
  city:"City",
  state:"State/Province",
  zipcode:"Zip Code",
  countrycallingcode:"Country calling code",
  country:"Country",
  paymentMethod:"Payment Method",
  cashondelivery:"Cash on Delivery",
  creditcard:"Credit/Debit Card",
  netbanking:"Net Banking",
  Orderdetails:"Order Details",
  placeorder:"Place Order",
  confirmorder:"Confirm Order",
  categories:"Categories",
  color:"Colors",
  priceRange:"Price Range (PKR)",
  apply:"Apply",
  clearall:"Clear all",
  save:"Save",
  orderid:"Order ID : #",
  tracking:"Tracking",
  delivered:"Delivered",
  addnewadress:"Add New Address",
  off:"off",
  discount:"Discount",
  redeem:"Redeem",
  expires:"Expires",
  rateyourexperiencewithus:"Rate your Experience with Us",
  recenttransaction:"recent tRANSACTION",
  thankyouforshopping:"Thank you for Shopping",
  save:"Save",
  testText:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis.",
  ops:"Oops!",
  congras:"Congratulation",
  congrasMessage:"Now Login with same crediential",
  updateMessage:"Please again Login",
  registered:"Registered",
  okay:"Okay",
  alertMessage:"Please Login First",
  addtocart:"has added to Cart",
  addtowhishlist:"has added to WhishList",
  recordupdate:"Record has Updated!",
  cart:'Cart',
  themeselection:"Choose Theme"
}
export default { font, icons, strings, colors, images }
